### ISSUE TITLE
Create Quick Stats endpoint

### ISSUE THREAD

**Issue by kiikoh** [kiikoh/Rowlog-FE#1]
Currently, this will consist of the meters per class. Possibly could be expanded but it may not be necessary.

Leave a response like this

```
{
                freshman: 1,
                sophomore: 1,
                junior: 1,
                senior: 1
}
```

**Comment by rmdmattingly** [comment]
`https://rows.tech/api/leaderboard/classWarfare?teamCode=`
Should handle this
